# LanceDB vector database

In [1]:
import lancedb

# i python såmåste det vara Path()
db = lancedb.connect(uri="vector_database")
db

LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database')

In [2]:
db.uri

'c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'

## Read in data

In [37]:
import json

with open("data/animals_text_embeddings.json", "r") as file:
    data = json.loads(file.read())

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

In [4]:
db.create_table("animals", exist_ok=True, data=data)

LanceTable(name='animals', version=2, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [5]:
db.list_tables()

ListTablesResponse(tables=['animals'], page_token=None)

In [6]:
db["animals"]

LanceTable(name='animals', version=2, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [7]:
db["animals"].head()

pyarrow.Table
text: string
vector: fixed_size_list<item: float>[3]
  child 0, item: float
----
text: [["A small brown dog running.","A cat resting quietly on a sofa.","A large gray elephant drinking water.","A fast cheetah sprinting across the savannah.","A colorful parrot perched on a branch."]]
vector: [[[0.12,0.85,0.33],[0.4,0.91,0.1],[0.88,0.22,0.55],[0.95,0.12,0.72],[0.25,0.66,0.81]]]

In [8]:
df_animals = db["animals"].to_pandas()
df_animals

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [9]:
df_animals.iloc

## To add more data

In [10]:
more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]

db["animals"].add(more_data)

AddResult(version=3)

In [11]:
db["animals"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
8              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
9               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

## Create empty table
- Create an empty table first, then place in data
- Need to provide schema

In [12]:
from lancedb.pydantic import LanceModel

class EmployeeSchema(LanceModel):
    first_name: str
    last_name: str
    salary: int

db.create_table(name = "employees",schema=EmployeeSchema, exist_ok=True)

LanceTable(name='employees', version=1, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [13]:
data = [{"first_name": "Bibbi", "last_name": "Babblarna", "salary": 1000}]
db["employees"].add(data)

AddResult(version=2)

In [14]:
db["employees"].to_pandas()

  first_name  last_name  salary
0      Bibbi  Babblarna    1000

In [15]:
db.list_tables()

ListTablesResponse(tables=['animals', 'employees'], page_token=None)

In [16]:
db.drop_table("employees")

In [17]:
db.list_tables()

ListTablesResponse(tables=['animals'], page_token=None)

# Vector search
ANN - approximate nearest neighbour for a vector search

1. send in a quesry vector directly and search  
    - this requires that we embed out quesry first using same embedding as what was used in the knowledge base
2. send in a text and let lancedb automaticly embed in and search

In [18]:
db["animals"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
8              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
9               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [19]:
# asume that we embed our question using same embedding model as the one for animals
# question about elephant
query_vector = [0.9, 0.2, 0.5]
db["animals"].search(query_vector).limit(4).to_pandas()

,text,vector,_distance
0,A large gray elephant drinking water.,"[0.88, 0.22, 0.55]",0.0033
1,A lion roaring loudly on a rock.,"[0.93, 0.18, 0.41]",0.0094
2,A lion roaring loudly on a rock.,"[0.93, 0.18, 0.41]",0.0094
3,A fast cheetah sprinting across the savannah.,"[0.95, 0.12, 0.72]",0.0573

## Embeddings API

- let lancedb embed our documents automatically
- let lancedg embed out quesry automatically and search using natural language

In [23]:
from lancedb.pydantic import Vector
from lancedb.embeddings import get_registry
from dotenv import load_dotenv

load_dotenv()

model = get_registry().get("gemini-text").create(name="gemini-embedding-001")
model

GeminiText(max_retries=7, name='gemini-embedding-001', query_task_type='retrieval_query', source_task_type='retrieval_document')

In [ ]:
embeddings = model.generate_embeddings("Why are databases good at relationships? Because they are relational")

[[-0.024318507,
  0.021380683,
  0.0118576065,
  -0.058168266,
  -0.028883407,
  0.011489711,
  -0.0022447465,
  0.014321048,
  0.011712493,
  -0.00023437424,
  0.012327072,
  -0.014833164,
  -0.0014773919,
  0.034879602,
  0.098589525,
  0.00044369575,
  0.013094193,
  0.007379488,
  0.006603937,
  0.005444807,
  0.013081205,
  -0.01289585,
  0.013336445,
  -0.0007170391,
  0.010834224,
  0.0009772424,
  0.006912347,
  -0.003631615,
  0.05108864,
  0.00036124472,
  0.0036054675,
  0.013380892,
  0.016712347,
  -0.0009248801,
  -0.004533899,
  0.0014884515,
  0.011677108,
  0.0037706646,
  -0.008544303,
  0.0026787387,
  0.00046600803,
  -0.006032636,
  0.029163595,
  -0.006803228,
  -0.011050768,
  0.0052175187,
  0.0064113275,
  -0.0076469267,
  -0.014462639,
  0.029349009,
  0.008311669,
  -0.025334226,
  -0.013655366,
  -0.14455642,
  0.022412555,
  -0.0067298426,
  -0.026344718,
  -0.01991177,
  -0.009647511,
  -0.0030755263,
  0.0016011818,
  -0.0054774648,
  -0.01269149,
  -0.003975102,
  -0.008159368,
  -0.0033851718,
  0.010054016,
  0.014348086,
  -0.00033946303,
  0.027551187,
  0.014289833,
  0.003965701,
  0.0083822645,
  -0.019148596,
  0.015234228,
  -0.014611191,
  -0.011655435,
  0.006163493,
  -0.016341744,
  0.039342795,
  0.017094703,
  -0.021384574,
  -0.00916798,
  -0.0060997773,
  0.011217382,
  0.013150515,
  -0.0071513364,
  -0.0030707184,
  -0.0114560025,
  -0.007156378,
  0.0042649005,
  0.0046616145,
  -0.010521305,
  0.0015375075,
  0.00069395755,
  -0.0188206,
  0.006029546,
  -0.00860648,
  -0.002687991,
  0.0067239245,
  0.0054510036,
  -0.040611465,
  -0.008558632,
  -0.023454253,
  0.014597936,
  -0.014254191,
  0.0013423846,
  -0.0068630087,
  0.011941841,
  -0.005829354,
  -0.017461328,
  0.0048063,
  0.022210736,
  0.01271094,
  0.009346739,
  -0.21015915,
  0.010903567,
  -0.018308131,
  -0.02152466,
  0.011276583,
  0.026464576,
  0.0025855189,
  0.007875979,
  -0.0036119015,
  -0.0014324236,
  0.0052586254,
  -0.0053689275,
  0.01864241,
  0.009524298,
  0.016457466,
  -0.002086613,
  -0.0058174795,
  -0.008372298,
  0.00023704256,
  0.014889308,
  0.0050062286,
  -0.016275508,
  0.006797493,
  -0.0022033658,
  0.0100917155,
  -0.0031305924,
  0.02592244,
  -0.018233597,
  0.026081035,
  -0.017627966,
  0.018185137,
  -0.009887259,
  0.01688392,
  0.0071220975,
  -0.006772933,
  -0.010147223,
  0.006081734,
  -0.008853465,
  0.012078966,
  0.01694995,
  -0.05211265,
  -0.0033182076,
  -0.004811399,
  0.008850223,
  0.014645931,
  0.0015256172,
  -0.0032485686,
  0.005467961,
  0.0076841647,
  0.002471952,
  0.0037537331,
  -0.023358526,
  0.016984187,
  -0.0048836926,
  0.015424317,
  -0.008367852,
  0.0006817927,
  -0.009746628,
  -0.0054216315,
  0.00079289207,
  -0.019972468,
  0.01407161,
  0.019994583,
  -0.023606004,
  -0.017927941,
  0.02527267,
  -0.03682768,
  -0.00036220613,
  -0.01372524,
  -0.007753263,
  -0.008728079,
  0.0070330515,
  0.028671227,
  -7.0319766e-06,
  0.0013830642,
  -0.016442832,
  0.00492371,
  0.018395504,
  -0.0046962523,
  0.013863164,
  0.009412425,
  -0.017998716,
  0.0036492578,
  -0.002053431,
  -0.009124467,
  -0.0035475364,
  -0.02535275,
  0.017271524,
  -0.002517094,
  0.008020705,
  0.0006676645,
  0.021390775,
  -0.00716553,
  0.02027204,
  -0.004468248,
  0.015106286,
  0.0059893364,
  0.024105199,
  0.013262848,
  0.029767478,
  -0.010452159,
  0.0017392999,
  0.010321044,
  0.015066468,
  -0.024601959,
  0.016105851,
  -0.0067018415,
  -0.012230291,
  -0.008622392,
  0.01597716,
  -0.0135125,
  0.011993769,
  -0.0041071135,
  -0.008504432,
  0.0043256213,
  -0.0002901779,
  0.017957728,
  -0.01480825,
  0.009543903,
  -0.016828023,
  0.02854579,
  -0.012159551,
  -0.016535543,
  0.020737598,
  -0.018991726,
  0.012336006,
  -0.012017566,
  0.004514011,
  0.00090214226,
  0.028077522,
  0.0004404502,
  0.009961832,
  0.00218567,
  0.012531817,
  -0.007958678,
  0.0050954134,
  0.032219138,
  0.017004604,
  -0.04028449,
  0.023736654,
  -0.037547152,
  -0.0025136496,
  -0.022568041,
  -0.007872597,
  0.012251913,
  -0.007991403,
  -0.019972624,
  0.0070436844,
  -0.00788504,
  -0.009481112,
  -0.016563691,
  0.00014378525,
  0.012180566,
  0.01948051,
  -0.0030998397,
  0.013230747,
  -0.00756562,
  -0.0020526235,
  0.014523559,
  -0.011846796,
  -0.00080412964,
  -0.14491287,
  0.0038198018,
  0.01833698,
  -0.01064768,
  -0.015245782,
  0.03418372,
  0.027045166,
  0.009206933,
  0.017295977,
  0.010095826,
  -0.018935442,
  -0.0046775285,
  0.012253697,
  -0.0014957974,
  -0.010090068,
  -0.01189107,
  -0.000507957,
  -0.012195481,
  0.0071100877,
  -0.009255303,
  0.0028340549,
  -0.005404589,
  0.014904659,
  -0.004300036,
  -0.0013604315,
  0.011522891,
  0.010730735,
  0.04182575,
  0.0014739409,
  0.011408002,
  -0.009288637,
  -0.018220574,
  0.02198476,
  0.0007993242,
  -0.0037912915,
  -0.008329734,
  -0.007835826,
  -0.015102826,
  -0.014700064,
  -0.010196623,
  0.008400364,
  -0.0061154864,
  0.0058756364,
  0.008928709,
  0.0154681085,
  0.0013685494,
  -0.007942026,
  -0.01036218,
  0.027829072,
  -0.010298903,
  0.0009139628,
  0.00029919756,
  0.026381498,
  -0.0011476588,
  -0.0018681806,
  -0.009836067,
  -0.0011157263,
  -0.0076557496,
  0.0034731545,
  -0.018780624,
  0.037685446,
  -0.013095017,
  -0.013833699,
  0.00034508234,
  0.0006479833,
  -0.002592599,
  -0.011545536,
  0.013173402,
  0.0260009,
  0.00045450332,
  0.00048146746,
  0.0024112193,
  -0.012707005,
  -0.027694266,
  0.003543015,
  0.015012253,
  0.01672326,
  -0.006083097,
  -0.0008464079,
  0.021328898,
  -0.010744076,
  0.007878883,
  -0.0047699027,
  -0.0009394565,
  0.008737923,
  0.011447886,
  0.016021304,
  -0.011929639,
  0.002503844,
  -0.02034946,
  0.0030212488,
  0.003739901,
  0.0120283235,
  -0.009189894,
  -0.013638148,
  -0.017416496,
  -0.017052993,
  0.006049852,
  0.0058225095,
  0.014212755,
  -0.026192755,
  -0.012534923,
  0.02869346,
  0.01236024,
  0.010163397,
  0.017711809,
  0.0029390003,
  0.011744626,
  -0.0022101607,
  0.00040163688,
  0.013454223,
  -0.004158077,
  0.02259905,
  0.017812988,
  0.016715473,
  -0.014425627,
  -0.0058688233,
  0.012717507,
  -0.009287108,
  0.012205682,
  -0.0007954785,
  -0.0052184616,
  0.0040097414,
  0.039340414,
  -0.0037969626,
  -0.005215452,
  -0.011667787,
  0.02477231,
  0.004220144,
  -0.003291056,
  -0.011466724,
  0.013748874,
  -0.0009633947,
  -0.005632413,
  -0.017210597,
  -0.008863904,
  -0.008205032,
  -0.020399107,
  0.012421726,
  0.008980799,
  -0.016195046,
  -0.014459456,
  0.010603278,
  -0.020779405,
  0.013529911,
  0.015505133,
  -0.014275045,
  0.0028945282,
  -0.0013777218,
  -0.009656324,
  0.0069201184,
  -0.0021719283,
  -0.00277242,
  0.017278863,
  0.0038220577,
  0.010927792,
  -0.0059898216,
  -0.011298049,
  -0.00063047005,
  -0.03640216,
  -0.00226774,
  -0.0022099782,
  -0.008943791,
  0.019145545,
  0.015794365,
  -0.012963793,
  0.01829841,
  -0.0036634398,
  -0.005220708,
  0.007956132,
  0.019210702,
  -0.0050555253,
  -0.01558044,
  -0.0049608,
  0.0011581937,
  0.014111288,
  0.0020914583,
  0.029594451,
  0.004868519,
  -0.00411737,
  0.003935153,
  -0.0039447625,
  -0.014493825,
  0.017934682,
  -0.0017095323,
  -0.0017302344,
  -0.014303901,
  0.003877255,
  -0.012497632,
  0.023278233,
  -0.0017917848,
  -0.016628265,
  -0.006273006,
  0.015968097,
  -0.006352882,
  0.004313794,
  0.016778866,
  0.007469328,
  -0.0025138098,
  0.009429355,
  -0.020260513,
  0.016579274,
  0.013510391,
  0.020671237,
  0.005530731,
  -0.008769694,
  -0.02230338,
  0.0006216283,
  0.001390277,
  -0.006646896,
  -0.023171902,
  0.008473322,
  0.004707102,
  0.011816549,
  0.004291794,
  0.015296557,
  0.0019332457,
  0.0042848103,
  -0.019047424,
  0.00049778516,
  -0.0071453815,
  -0.016673904,
  0.004022816,
  0.0072623184,
  0.03129075,
  0.0058323257,
  -0.017252458,
  -0.009966172,
  0.0012757988,
  0.018105837,
  0.022022093,
  -0.022221528,
  -0.014027141,
  0.014878984,
  -0.0068022516,
  -0.012590315,
  0.0115434555,
  0.0057394304,
  0.01330465,
  0.005232493,
  -0.010066898,
  -0.023717703,
  -0.009246563,
  0.025731932,
  -0.0030569187,
  -0.013063585,
  -0.003488053,
  0.0018144118,
  -0.0035499395,
  -0.0050049536,
  0.0031295365,
  0.0054747686,
  0.0048175687,
  -0.013217598,
  0.0014131481,
  0.021891486,
  -0.005499218,
  0.012366014,
  -0.0024966656,
  -0.0035191127,
  0.0057933447,
  -0.027755128,
  -0.009113801,
  0.030100452,
  -0.0012570977,
  0.010406835,
  0.013191133,
  0.016059788,
  -0.017553186,
  -0.11760953,
  -0.015624858,
  -0.018436953,
  -0.03339519,
  0.010301737,
  -0.006194397,
  -0.00073687325,
  0.012400099,
  -0.00483898,
  -0.00021911568,
  0.010198984,
  0.010678653,
  0.011736771,
  -0.0012053318,
  0.020659225,
  -0.018838692,
  0.006374965,
  0.0107524805,
  -0.00072325155,
  0.007719328,
  -0.009179317,
  0.005357131,
  0.0063140825,
  0.01765102,
  -0.00076746254,
  -0.014913588,
  -0.00841122,
  -0.006381777,
  0.0072313123,
  0.019837752,
  -0.01801874,
  -0.008801851,
  0.0069782953,
  0.00468689,
  -0.0066496218,
  0.018092232,
  0.00011366164,
  -0.014242917,
  0.011796421,
  0.01961692,
  0.012646964,
  0.005049568,
  -0.0022770546,
  0.0026512735,
  -0.007854873,
  0.0078907525,
  0.00448157,
  -0.021466043,
  0.0017047146,
  0.0007750801,
  -0.02399801,
  0.019763933,
  0.0096104685,
  -0.0075226077,
  0.004455656,
  -0.015610573,
  -0.0034265658,
  -0.0082271,
  -0.010112144,
  -0.026812902,
  -0.0071342266,
  0.022498017,
  -0.0047277785,
  0.02085945,
  -0.020937622,
  0.008402485,
  0.0124110645,
  -0.0026187,
  0.014185989,
  -0.027477672,
  0.03003456,
  -0.0066516534,
  -0.0052627265,
  0.0053905514,
  -0.00878851,
  0.045484893,
  0.016853962,
  0.015287188,
  0.010112743,
  0.0011901646,
  0.00019718846,
  0.0010841439,
  -0.092963904,
  -0.0033543773,
  -0.010752369,
  -0.010485124,
  0.008559716,
  0.013753789,
  0.00086241966,
  0.0073544527,
  -0.0019138716,
  -0.01994844,
  -0.01893204,
  6.4322725e-05,
  -0.01377127,
  0.006224555,
  -0.008947283,
  -0.002118488,
  -0.01007186,
  0.016132804,
  0.002416255,
  0.01213022,
  0.005646737,
  0.0055775424,
  0.0039915787,
  -0.0023896205,
  -0.0041968147,
  0.018276466,
  -0.011678633,
  0.021603048,
  0.03398464,
  -0.011322833,
  0.034762353,
  -0.1312863,
  0.016738966,
  0.02134472,
  0.019279871,
  0.006928286,
  0.00049205334,
  -0.01251808,
  0.007879008,
  -0.01933953,
  -0.0074029625,
  -0.015176153,
  -0.0118164625,
  -0.01921744,
  -0.018167125,
  0.004024656,
  0.16485511,
  0.0048653698,
  -0.02209075,
  0.0036987264,
  -0.0077317157,
  0.013850536,
  -0.014743513,
  0.012486368,
  0.008474252,
  0.00963928,
  -0.0021044451,
  -0.011595388,
  -0.012592161,
  0.0052595073,
  0.013282157,
  0.014453541,
  0.008887179,
  0.006828457,
  0.0037672778,
  -0.00046252538,
  -0.0011481497,
  0.017897168,
  0.009441184,
  -0.007651487,
  0.006399377,
  -0.012584245,
  0.00070951204,
  -0.026018802,
  0.0018337943,
  -0.02528714,
  0.0065075974,
  0.01534449,
  -0.011490343,
  0.006583474,
  0.0029690466,
  -0.018890142,
  -0.077372424,
  0.012616073,
  0.0028029203,
  0.016581528,
  -0.005608796,
  -0.010728848,
  -0.011604423,
  -0.008438408,
  -0.0017417023,
  0.00044652817,
  -0.010287768,
  0.011523339,
  -0.0056944946,
  0.0031852063,
  -0.022714514,
  -0.01854416,
  0.009929677,
  0.011667508,
  0.008849337,
  0.0008565731,
  -0.0066259303,
  0.008856227,
  -0.010298287,
  0.006075335,
  -0.038782384,
  0.008608318,
  0.009346377,
  -0.0033722552,
  -0.007011341,
  0.0023781727,
  -0.0017417228,
  0.0011061555,
  -0.016295778,
  -0.011474067,
  -0.014931634,
  -0.0065688775,
  0.032018237,
  0.008208628,
  -0.008045231,
  0.023645898,
  0.01937804,
  -0.004199844,
  -0.015195547,
  -0.006386634,
  0.0038377915,
  -0.031158239,
  -0.009046316,
  -0.006247243,
  -0.00039374531,
  0.016003713,
  -0.011040537,
  0.018628823,
  -0.022667991,
  0.010462552,
  -0.008892235,
  0.006458528,
  0.005211703,
  -0.005026836,
  -0.019454943,
  -0.0039537502,
  0.0029908805,
  0.0036945012,
  0.00636776,
  0.011426387,
  0.006142181,
  -0.010939165,
  0.02515823,
  -0.0007005561,
  -0.005450392,
  0.002158048,
  0.023319347,
  0.013134247,
  0.015013769,
  0.013832069,
  0.012681951,
  -0.0074837804,
  0.012488143,
  0.011297911,
  0.002721665,
  -0.006761684,
  -0.0074566295,
  -0.0011150042,
  -0.0076287356,
  -0.0022697807,
  -0.0060569076,
  0.0038128793,
  -0.003625788,
  0.012368843,
  -0.014661682,
  0.005478007,
  -0.011968311,
  -0.01414852,
  -0.00801323,
  -0.0035415431,
  0.0036061709,
  0.008388757,
  -0.005394374,
  -0.019520808,
  -0.017713137,
  -0.005842146,
  -0.0027672704,
  0.009070104,
  0.004807377,
  0.0011729255,
  -0.0015089748,
  -0.00039962283,
  -0.0038417203,
  -0.0118735945,
  -0.0010978215,
  0.004943704,
  0.01255682,
  -0.009596358,
  0.009950505,
  0.01362949,
  -0.0024614404,
  -0.003208259,
  -0.012578629,
  0.00030597879,
  -0.0038454041,
  0.0039893077,
  0.01398739,
  0.0031028963,
  0.008765384,
  -0.01431151,
  0.0012309011,
  -9.0119e-05,
  -0.0027151867,
  -0.045523014,
  0.00064288266,
  -0.0016621493,
  -0.0035882338,
  -0.013586787,
  0.003928858,
  -0.011220918,
  0.009936243,
  -0.0070872037,
  0.003098191,
  -8.258479e-05,
  -0.006579198,
  0.0013644965,
  -0.0040201684,
  0.017501364,
  -0.002897165,
  0.0090622315,
  0.014391383,
  -0.012819806,
  -0.0024415895,
  -0.0029139393,
  -0.00070517097,
  0.000675171,
  0.0011534091,
  0.014559034,
  -0.0042162165,
  0.007174272,
  0.009294856,
  0.0024689327,
  0.011787713,
  -0.0068798875,
  0.010215488,
  -0.015620196,
  0.010184081,
  0.00066037115,
  0.0012029094,
  -0.005737135,
  -0.013977026,
  -0.019584911,
  0.008056569,
  0.006451473,
  -0.0120169,
  0.018346203,
  -0.0007382385,
  0.01140879,
  0.0018887671,
  0.010147528,
  -0.004395872,
  -0.0012674197,
  0.011003695,
  0.01573369,
  0.0022516644,
  -0.0051107877,
  0.0052024066,
  0.0154111,
  0.011100193,
  0.006779714,
  0.002863984,
  0.02588239,
  0.007154872,
  0.034681756,
  0.012421341,
  8.976523e-05,
  0.01843626,
  0.014829954,
  0.010278336,
  0.0044183303,
  0.0046082307,
  -0.010520781,
  0.001174345,
  -0.013023046,
  0.005178419,
  -0.0035993569,
  0.011256676,
  -0.0021947352,
  0.013415389,
  -0.0038467825,
  -0.028623456,
  -0.006005721,
  0.009326003,
  -0.007048953,
  -0.0024960518,
  -0.003993065,
  0.0037671432,
  -0.013882394,
  -0.015522308,
  0.0066019166,
  -0.013463594,
  0.002072693,
  -0.0043370663,
  -0.008946857,
  0.0038361885,
  0.0016735778,
  0.0057232324,
  -0.001538335,
  -0.010226086,
  0.0126557015,
  0.0035883856,
  -0.0081535755,
  0.0057304567,
  -0.01733243,
  0.006400462,
  -0.0115063535,
  -0.010444716,
  0.00808802,
  -0.0038847376,
  0.0027870077,
  -0.0025697148,
  0.0058322637,
  0.012471347,
  0.006407926,
  -0.009641321,
  0.0045587574,
  0.0026992888,
  -0.0014397544,
  0.014896084,
  -0.0037749277,
  -0.0078055,
  -0.0028500608,
  0.02456186,
  -0.00216721,
  -0.009388407,
  0.012369505,
  -0.0061265365,
  0.016944794,
  0.00010163238,
  0.0026258386,
  0.010698309,
  0.015844041,
  0.014726667,
  -0.0015021391,
  -0.008412483,
  0.10162543,
  0.022742597,
  0.009469356,
  0.005947309,
  0.001274509,
  -0.008010566,
  -0.0015639374,
  -0.010952361,
  0.0017550327,
  0.006322468,
  -0.0012558181,
  0.00281771,
  -0.011046224,
  0.0030254573,
  0.007397921,
  0.007755974,
  0.017510472,
  0.012309937,
  -0.004347572,
  -0.014175636,
  0.006861688,
  0.015569563,
  -0.008214728,
  -0.0124858245,
  0.0063710026,
  0.0028757358,
  0.005491,
  -0.004896798,
  0.00612346,
  0.0044064354,
  -0.0005578374,
  0.0074831084,
  ...],
 [-0.010894743,
  -0.0028489418,
  0.00893425,
  -0.054541513,
  -0.007433747,
  0.017504206,
  0.014653749,
  0.02498823,
  0.01153613,
  -0.004031619,
  0.0019689437,
  -0.015896015,
  -0.0033653777,
  0.015975969,
  0.09177606,
  -0.02413529,
  0.026621163,
  -0.015998762,
  -0.009193494,
  -0.0032317825,
  0.017314918,
  -0.014104707,
  -0.000599844,
  -0.013850878,
  0.025816025,
  0.027195023,
  0.017755596,
  0.009800108,
  0.022374708,
  0.017374959,
  -0.0027653421,
  0.0067342324,
  0.00040601502,
  0.002778903,
  -0.004352005,
  0.011505135,
  0.022893922,
  -0.010107965,
  -0.0130854435,
  0.022383824,
  0.00030385726,
  -0.007134147,
  0.002239337,
  -0.0012981425,
  7.041567e-05,
  0.011082349,
  -0.005637078,
  -0.025727957,
  0.0059076254,
  0.0042295936,
  0.0017543633,
  0.011937581,
  -0.020759232,
  -0.14057352,
  -0.011109075,
  0.006916541,
  -0.0025381926,
  0.021703891,
  0.0076077846,
  -0.029725924,
  0.010393887,
  0.026465422,
  -0.014564507,
  -0.008960989,
  -0.0278895,
  -0.013143821,
  0.025932917,
  0.018782737,
  -0.007277717,
  0.011100802,
  -0.007302172,
  0.0043212418,
  -0.0045143194,
  0.0043093036,
  -0.01031841,
  0.0069819386,
  0.0071304743,
  0.009563596,
  -0.012977294,
  0.042270605,
  -0.01831609,
  -0.028458375,
  -0.014239028,
  -0.011460251,
  0.0006987148,
  0.0037828432,
  -0.011120268,
  -0.007279127,
  -0.012551258,
  -0.0042546215,
  0.005001188,
  0.011654048,
  0.013459278,
  -0.026933843,
  0.005779235,
  -0.009201566,
  0.005145211,
  0.00490399,
  -0.0035683631,
  0.0068511767,
  0.011755284,
  -0.016186627,
  -0.0013286247,
  0.020250997,
  -0.013469695,
  -0.03154354,
  0.008879823,
  0.006014098,
  -0.012009428,
  -0.003291308,
  -0.00082919054,
  0.009012183,
  0.019133175,
  0.008885957,
  0.0043297824,
  -0.20751265,
  0.008460281,
  -0.017181886,
  -0.006850679,
  0.010617436,
  0.011536425,
  -0.0071962243,
  -0.0010271898,
  -0.006679142,
  -0.0077334,
  -0.018232046,
  0.0034199327,
  -0.0018284925,
  -0.0136822825,
  -0.010364635,
  0.0016082462,
  0.012740099,
  0.020895476,
  -0.028925855,
  0.022254398,
  0.020805182,
  -0.017180556,
  0.004820916,
  -0.000992084,
  0.008635904,
  0.006466806,
  -8.019128e-05,
  0.024454331,
  0.019131053,
  -0.014722803,
  0.0062699057,
  -0.022018414,
  -0.017078115,
  0.0022915488,
  -0.027813174,
  -0.010954208,
  -0.0028691404,
  -0.017401146,
  -0.0014321284,
  0.0045618964,
  -0.053670872,
  -0.0017024488,
  0.011066855,
  0.02336727,
  0.0072743143,
  0.028426943,
  -0.0038358436,
  0.0015755467,
  0.0045387973,
  -0.019761046,
  -0.006387864,
  -0.002886542,
  -0.013430993,
  -0.004872644,
  0.010991768,
  -0.010491402,
  0.004218905,
  0.0005331038,
  0.009074472,
  0.006245508,
  -0.018454002,
  0.013116634,
  0.008405044,
  -0.02607379,
  -0.0024505388,
  0.016906098,
  -0.002226631,
  0.017387604,
  -0.01681773,
  0.0014685016,
  -0.015496952,
  0.0031811313,
  -0.020021455,
  -0.014221316,
  -0.017845353,
  -0.0042030164,
  0.009824213,
  -0.004035922,
  -0.0042756153,
  -0.0013127609,
  0.016973812,
  -0.029653305,
  0.013411013,
  0.012157935,
  -0.019172492,
  0.0033376457,
  -0.023614703,
  0.017573183,
  0.00020139631,
  -0.008571299,
  0.009848198,
  0.00048534037,
  -0.011776163,
  0.011511077,
  0.010927528,
  -0.0093797585,
  -0.0067883017,
  0.009523407,
  -0.0031142263,
  0.014011795,
  0.019919202,
  -0.008621176,
  -0.0027430984,
  -0.009397683,
  0.0003848104,
  0.03421796,
  -0.003793513,
  -0.014944244,
  0.006584726,
  0.0041904184,
  -0.007230043,
  -0.0063115098,
  -0.013932514,
  -0.0030269139,
  0.004997075,
  0.0036656752,
  0.001233697,
  -0.0021096815,
  0.016758723,
  -6.737517e-05,
  0.008696733,
  0.02239819,
  0.013805341,
  0.026058985,
  -0.003100445,
  -0.0017851377,
  -0.014138923,
  -0.0014701751,
  0.010721434,
  0.005706593,
  0.010899184,
  0.006407311,
  -0.0027334483,
  0.010179657,
  0.0024023175,
  0.012393262,
  0.012551334,
  -0.0046072192,
  -0.0073801847,
  0.0097025195,
  0.008116727,
  -0.0027904492,
  -0.016621532,
  -0.01861488,
  -0.017483005,
  0.015929664,
  -0.014126334,
  -0.032372747,
  0.029368991,
  0.02189217,
  0.017452128,
  -0.0012530104,
  0.02122505,
  -0.0021632616,
  0.014150737,
  0.015274288,
  -0.020296065,
  -0.030935528,

In [28]:
import numpy as np
np.array(embeddings).shape

(68, 3072)

In [29]:
class JokeModel(LanceModel):
    joke: str = model.SourceField() #Input to embedding function
    embedding: Vector(3072) = model.VectorField() #Computed embedding in this column

db.create_table("jokes", schema=JokeModel, exist_ok=True)

LanceTable(name='jokes', version=1, _conn=LanceDBConnection(uri='c:\\Skolprojekt\\ai_engineering\\ai_engineering_jonas_gustafsson\\code-alongs\\13_lancedb\\vector_database'))

In [35]:
import pandas as pd

with open("data/jokes.json", "r", encoding="utf-8") as file:
    jokes_data = json.loads(file.read())